version: '3.5'

services:
  verdaccio:
    container_name: verdaccio-npm-repository
    image: verdaccio/verdaccio
    restart: always
    ports:
      - 4873:4873
    volumes:
      - ./config/conf:/verdaccio/conf
      - ./config/storage:/verdaccio/storage
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
